apiVersion: v1
kind: Secret
metadata:
  name: ZGVwaQ==
  # corresponds to user.spec.passwordSecretKeyRef.name
type: Opaque
data:
  password: ZGVwaQ==
  # corresponds to user.spec.passwordSecretKeyRef.key