apiVersion: v1
kind: Secret
metadata:
  name: organization-secret
  namespace: mongodb
stringData:
  user: depi
  publicAPIKey: eyJvcmdJZCI6IjY2ZTE0ZTk5NTYxMzU5N2ZiYWViNDY4ZSIsIm9yZ05hbWUiOiJtb2hhbWVkIGhlbGxhbCIsInByaXZhdGVBcGlLZXkiOiIxNTY4MzY1Yi0zZDIwLTQ5ZWEtYmY5YS00MmJiNjUyM2MwNDMiLCJwdWJsaWNBcGlLZXkiOiJyYndjcHZrYiJ9